# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Ageish"
email: ageish@fameexpress.com
description: >- # this means to ignore newlines until "baseurl:"
  Ageish is your trusted resource to live your best mid-life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ageish.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ageish_
permalink: /:title:output_ext

# Social and SEO settings
author: Ageish Team
logo: /assets/images/logo.webp
lang: en_US
social:
  name: Ageish
  links:
    - https://twitter.com/ageish_
    - https://www.facebook.com/ageish
    - https://www.linkedin.com/company/ageish

# Google Analytics - replace UA-XXXXXXXX-X with your tracking ID if using
google_analytics: UA-XXXXXXXXX-X

# Build settings
# theme: minima
remote_theme: wowthemesnet/mediumish-theme-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

# Mediumish theme settings
paginate: 10
paginate_path: /page:num/

# Authors
authors:
  ageish_team:
    name: Ageish Team
    display_name: Ageish Team
    gravatar:
    email: ageish@fameexpress.com
    web: https://www.ageish.com
    twitter: https://x.com/ageish_
    description: "The Ageish Team provides resources and support for the Sandwich Generation."

# Markdown
markdown: kramdown
highlighter: rouge

# Comment out or remove the minima section as we're no longer using it
# minima:
#   skin: classic
#   social_links:
#     twitter: ageish_

excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - favicon.ico
  - favicon-16x16.png
  - favicon-32x32.png
  - apple-touch-icon.png
  - android-chrome-192x192.png
  - android-chrome-512x512.png
  - site.webmanifest
